//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LunarClock.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LunarClock.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap First_Quater {
            get {
                object obj = ResourceManager.GetObject("First Quater", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to During the First Quarter, 
        ///half of the moon lights up. 
        ///In the Northern Hemisphere, 
        ///the right side is lit up 
        ///and vice versa for the 
        ///Southern Hemisphere.
        ///
        ///This is the period where you 
        ///should tweak the intentions
        ///made during the New Moon.
        ///Use the momentum of this 
        ///phase to overcome resistences
        ///and make decisions..
        /// </summary>
        public static string First_Quater_Description {
            get {
                return ResourceManager.GetString("First_Quater_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Full_Moon {
            get {
                object obj = ResourceManager.GetObject("Full Moon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Full Moon is the phase 
        ///where the moon is the most 
        ///luminant. It occurs when the 
        ///earth finds itself between 
        ///the sun and marks the middle
        ///of the lunar cycle.
        ///
        ///This is known to be the most 
        ///powerful phase and is a time 
        ///where everything comes 
        ///together. This is when you
        ///should celebrate everything
        ///that you have achieved..
        /// </summary>
        public static string Full_Moon_Description {
            get {
                return ResourceManager.GetString("Full_Moon_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Lunar_Background {
            get {
                object obj = ResourceManager.GetObject("Lunar Background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Lunar_Cycle {
            get {
                object obj = ResourceManager.GetObject("Lunar Cycle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap New_Moon {
            get {
                object obj = ResourceManager.GetObject("New Moon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The New Moon is the first 
        ///phase of the moon, it is 
        ///also known as the Dark Moon 
        ///and represents new beginnings 
        ///and fresh starts and is when
        ///intentions are created.
        ///
        ///This is the period where you 
        ///should try new things and 
        ///start new adventures. It is 
        ///a good time to open yourself 
        ///up for change and be on the 
        ///look out for new opportunities..
        /// </summary>
        public static string New_Moon_Description {
            get {
                return ResourceManager.GetString("New_Moon_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Stars_Background {
            get {
                object obj = ResourceManager.GetObject("Stars Background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Third_Quater {
            get {
                object obj = ResourceManager.GetObject("Third Quater", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to During the Third Quarter, 
        ///half of the moon lights up. 
        ///In the Northern Hemisphere, 
        ///the left side is lit up 
        ///and vice versa for the 
        ///Southern Hemisphere.
        ///
        ///This is the period where you
        ///should officially cut ties
        ///with things we no longer need.
        ///This is when you should clean
        ///up and let go in order to
        ///make room for new things..
        /// </summary>
        public static string Third_Quater_Description {
            get {
                return ResourceManager.GetString("Third_Quater_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Waning Crescent Moon is 
        ///the last phase in the lunar 
        ///cycle. It appears as a 
        ///silver crescent and is when 
        ///you should start to relax 
        ///and not push yourself.
        ///
        ///You should finally be at 
        ///piece on this phase and
        ///should feel complete. 
        ///Organise the memories that
        ///you have created and prepare
        ///yourself for the next cycle..
        /// </summary>
        public static string Waning_Crescent_Description {
            get {
                return ResourceManager.GetString("Waning_Crescent_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Waning Gibbous Moon is 
        ///the phase that comes 
        ///directly after the Full Moon.
        ///It represents letting go and 
        ///beggining the process of
        ///banishing unwanted things.
        ///
        ///This is the period where you
        ///should contemplate how far
        ///you&apos;ve come from your set
        ///intentions. You should
        ///express graditude towards
        ///your accomplishments..
        /// </summary>
        public static string Waning_Gibbous_Description {
            get {
                return ResourceManager.GetString("Waning_Gibbous_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Waxing Crescent Moon 
        ///occurs right after the New 
        ///Moon. It appears as a silver
        ///crescent and represents 
        ///growth and gaining strength 
        ///towards goals.
        ///
        ///This is the period where
        ///you should start acting
        ///upon the intentions you
        ///made on the New Moon and is
        ///when you should really push
        ///yourself to accomplish..
        /// </summary>
        public static string Waxing_Crescent_Description {
            get {
                return ResourceManager.GetString("Waxing_Crescent_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Waxing Gibbous Moon 
        ///occurs two weeks after the 
        ///New Moon. It is the last
        ///phase before the Full Moon
        ///and is known to be the
        ///less powerful phase.
        ///
        ///This phase is the final
        ///push towards your goals.
        ///It is the period where you 
        ///should assess yourself and 
        ///learn from your mistakes
        ///to adapt and overcome..
        /// </summary>
        public static string Waxing_Gibbous_Description {
            get {
                return ResourceManager.GetString("Waxing_Gibbous_Description", resourceCulture);
            }
        }
    }
}
