//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LunarClock {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class LunarSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static LunarSettings defaultInstance = ((LunarSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new LunarSettings())));
        
        public static LunarSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime lastNewMoonS {
            get {
                return ((global::System.DateTime)(this["lastNewMoonS"]));
            }
            set {
                this["lastNewMoonS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool hasMoonDataS {
            get {
                return ((bool)(this["hasMoonDataS"]));
            }
            set {
                this["hasMoonDataS"] = value;
            }
        }
    }
}
